version: "3.7"
services:
  tomcat: 
    image: bfreitas/tomcat:1.0
    environment:
      - CATALINA_BASE=/opt/tomcat/apache-tomcat-8.5.100
      - CATALINA_HOME=/opt/tomcat/apache-tomcat-8.5.100
    ports:
      - 8080:8080 # HTTP
      - 4041:4041 # HTTPS
    volumes:
    - ./conf/server.xml:/opt/tomcat/apache-tomcat-8.5.100/conf/server.xml
    - ./certificates:/opt/tomcat/apache-tomcat-8.5.100/conf/certificates
